lib: [
  "_build/install/default/lib/ppx_fields_conv/META"
  "_build/install/default/lib/ppx_fields_conv/dune-package"
  "_build/install/default/lib/ppx_fields_conv/opam"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.a"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cma"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmi"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmt"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmti"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmx"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmxa"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.cmxs"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.ml"
  "_build/install/default/lib/ppx_fields_conv/ppx_fields_conv.mli"
]
doc: [
  "_build/install/default/doc/ppx_fields_conv/CHANGES.md"
  "_build/install/default/doc/ppx_fields_conv/LICENSE.md"
  "_build/install/default/doc/ppx_fields_conv/README.md"
]
